### ISSUE TITLE
HOW TO USE IT ON TF SERVING BATCH PREDICTION

### ISSUE THREAD

**Issue by anish9** [dhlab-epfl/dhSegment#36]
I have retrained the model using my own dataset, but when I try to get prediction using TF serving using gRPC API call I am not able to pass the images in a batch, it gives out dimensions error but when I pass single image I am able to get predictions. can some help with me on using this model on batch prediction when served.

**Comment by solivr** [comment]
Hello,

I think this is more a TF Serving issue, so you probably should have a look at their documentation.
But I also implemented a serving function which handles batches. If it can help, I'll clean the code and share it soon, hopefully.

**Comment by hiepph** [comment]
Hi @solivr any progress so far? And is it possible to input image instead of the path to image itself?

**Comment by solivr** [comment]
Hi @hiepph I just pushed the `batch_prediction` branch, have a look at it. Note that you need to add an additional parameter `saved_model_batch=True` in the config in order to use the `serving_input_filename_batch` function as serving function.
And when using the simple `serving_input_filename`, you can input an image with the [`from_image`](https://github.com/dhlab-epfl/dhSegment/blob/batch_prediction/dh_segment/io/input.py#L264) signature name. However this is not possible with `serving_input_filename_batch`, as the images need to be padded and this is handled within the function.

**Comment by lynx97** [comment]
> Hi @hiepph I just pushed the `batch_prediction` branch, have a look at it. Note that you need to add an additional parameter `saved_model_batch=True` in the config in order to use the `serving_input_filename_batch` function as serving function.
> And when using the simple `serving_input_filename`, you can input an image with the [`from_image`](https://github.com/dhlab-epfl/dhSegment/blob/batch_prediction/dh_segment/io/input.py#L264) signature name. However this is not possible with `serving_input_filename_batch`, as the images need to be padded and this is handled within the function.

Hi @solivr Are there any progress for serving prediction for `serving_input_image`
